# Generated by Django 5.1.6 on 2025-03-09 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_to',
            field=models.ManyToManyField(related_name='event', to=settings.AUTH_USER_MODEL),
        ),
    ]
